#!/usr/bin/env python3

import logging
from GyroBalancer import GyroBalancer


class BALANC3R(GyroBalancer):
    """
    Laurens Valk's BALANC3R
    http://robotsquare.com/2014/06/23/tutorial-building-balanc3r/
    """
    def __init__(self):
        GyroBalancer.__init__(self, # Q=[1,0,0,0,0;0,1,0,0,0;0,0,1,0,0;0,0,0,1,0;0,0,0,0,4e2],R=1e3*eye(3)でデジタルな方法で算出したゲインを使用
                              gainGyroAngle=31.7653,#30.2153, #900, # K_F[1]
                              gainGyroRate=3.5353,#3.3269, #110, # K_F[3]
                              gainMotorAngle=0.3949,#0.1606, #9, # K_F[0]
                              gainMotorAngularSpeed=1.1491*0.85,#1.0796 * 0.882625, # 妥当な係数は8.5〜9.0くらい？ # K_F[2] #
                              gainMotorAngleErrorAccumulated=0.1225*0.1)#0.4472)#0.0224) #3) # K_I


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s %(levelname)5s: %(message)s')
    log = logging.getLogger(__name__)

    log.info("Starting BALANC3R")
    robot = BALANC3R()
    robot.main()
    log.info("Exiting BALANC3R")
