PROGRAM = runner.so
OBJS = runner.o
CC = arm-linux-gnueabi-gcc
CFLAGS=`arm-linux-gnueabi-python3-config --cflags`
LDFLAGS=`arm-linux-gnueabi-python3-config --ldflags`
INCLUDES=`arm-linux-gnueabi-python3-config --includes`

.SUFFIXES: .c .o .so

.PHONY: all
all: $(PROGRAM)

runner.so: runner.o
	$(CC) $< -o $(PROGRAM) -shared $(LDFLAGS)
	make depclean

runner.o: runner.c
	$(CC) -c $< ${INCLUDES} $(CFLAGS)
